--Number of Patients by Department
SELECT department,
COUNT(*) AS TotalPatients
FROM PatientAnalytics
GROUP BY department
ORDER BY TotalPatients DESC;


--Average Treatment Cost by Department
SELECT department,
ROUND(AVG(treatment_cost),2) AS AvgTreatmentCost
FROM PatientAnalytics
GROUP BY department
ORDER BY AvgTreatmentCost DESC;

--Total Revenue Generated by Department
SELECT department,
ROUND(SUM(treatment_cost),2) AS TotalRevenue
FROM PatientAnalytics
GROUP BY department
ORDER BY TotalRevenue DESC;

--Average Length of Stay by Department
SELECT department,
ROUND(AVG(length_of_stay_days),2) AS AvgStay
FROM PatientAnalytics
GROUP BY department
ORDER BY AvgStay DESC;

--Average Recovery Score by Department
SELECT department,
ROUND(AVG(recovery_score),2) AS AvgRecoveryScore
FROM PatientAnalytics
GROUP BY department
ORDER BY AvgRecoveryScore DESC;

--Average Readmission Risk by Department
SELECT department,
ROUND(AVG(readmission_risk),2) AS AvgReadmissionRisk
FROM PatientAnalytics
GROUP BY department
ORDER BY AvgReadmissionRisk DESC;

--Emergency vs Routine Patients by Department
SELECT department,visit_type,
COUNT(*) AS TotalPatients
FROM PatientAnalytics
GROUP BY department, visit_type
ORDER BY department;

--Treatment Types in Each Department
SELECT department,treatment_type,
COUNT(*) AS TotalPatients
FROM PatientAnalytics
GROUP BY department, treatment_type
ORDER BY department, TotalPatients DESC;

--Department Performance Score
SELECT department,
COUNT(*) AS TotalPatients,
ROUND(AVG(treatment_cost),2) AS AvgCost,
ROUND(AVG(length_of_stay_days),2) AS AvgStay,
ROUND(AVG(recovery_score),2) AS AvgRecovery,
ROUND(AVG(readmission_risk),2) AS AvgReadmissionRisk
FROM PatientAnalytics
GROUP BY department
ORDER BY TotalPatients DESC;

--